language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - graphviz
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo run --verbose
before_deploy:
- git config --local user.name "Larry Fantasy"
- git config --local user.email "larry.fantasy@gmail.com"
- echo $GITHUB_TOKEN
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: README.md
  skip_cleanup: true
  draft: true
  on:
    tags: true
env:
  global:
  - secure: F+5k2XbaLIU/hbhGU5XeVCP/ep+2Z2f+FhOKew748NrIPaQKg0NRMOu096Donn+kwxOZ7j0Nx3gXGCOqDt3ur/faezWkD9tXr4QtduX2a3KDDrLiT7lznUXtcFD60ffTHjI4DL3m8zpS0EEoxhqYRwIMFmR7FEyMdPj5ayRF9PNeKL3zHlG043/OkfC9HC2sxgn/HAvIz8C8RhMtRTqGG7i85AUpzf64paX5kk2BE6WrhmbuhL7Jtd9TXGFrm9u0/P/PReiQHSuyuuNJWNBFk8HBVkQQShXiHghak4UWH31daSKihxFT+RuNvsB4LStLTaq023OVhzDU3GBL7ctT5wc6bVObdrXm+9RaJeMv3kFgu//urovm9kWySXYD4Q1OMxdHXbwoHFNax6Y7BawTqPZybNk4aEUy7+p4pcXTxA8zVK0tmLw9osTgmakrXoAWHo3BQguDuukN/FAZ5IiYbYUrn/9FLu0yebrFA3IXm2uyVLvqanq7sXYTnew1d3aGiBUJrKHimfbsx8Dv8/zEP/90kvp0wbGZh54mpjE3dli3Eg6uHBr7Hmf20EFWlTRYlZFBcrBNigA8CzxmxSyqckQmKOwTBzAN9Oe8R562dAbmpWkBRfeIaX3PD/uWitifsHOLjApqWRVsdNFHXpvlXL2b06iFq9cA2n+ZTPIxAsU=
  - secure: mQS6fOu+n9d6GKXln5DZoi25X+E2CYBa6U2SlRMo+bqwEvEWG19WtaU4PIrSulQIh1h+VUIVIl4AOvyUiLK7C1Y4QmhgmAUUdMoXBIWXfTcyLa1WdXTkVpS7VVhoOq3O9Fsggk8sEHSVt7qx/QEWGtc02oI0TiBeERVZs4TvrHfxNHKn768wAlOZZMTELjUOIHm/P1WMJBUoT+sNMGYr7dA5pte1JaGesEcze12lwx+rHlVu55ogkMY0PEDH/hnwEyRhWPPljksxw44IwdEJvSe81ZEKi8JpAABohlFbfLfLon/EPlI2cz8vlBvOR65iA9DofVx8V5d93K41g+FHnCf7GoPo3OOd8RoYt2aUs9byzxApCEnuWD9E9Qh0RaYSxSVnkk8czq3eL5Z67u75NyDOmTWoDTwqU7DCEj39wzQbAKTHx02IDSpkJAByATvUd2eJwvT789VawG5Uze9FuhB/QxheS5UW9Xl1UlAhTJtINrPiewvMwm3OQgc5o+TtzM635XJTwhH+wfRHU1nYZeK5v78f/QQjYOt4ul6yrqPLcinGdE027MnpOL0jnJOGDoXx41ipZASNAOryHFtikp04U+4nHgOu7+I3PmrLFGl7YZ5Lwv/xdRo4mFfCpoSRHCIMpE+x9LDhu3EkurL6loKyzF2H/Jkp5dPmLQjcTDg=
