language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - graphviz
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo run --verbose
before_deploy:
- git config --local user.name "Larry Fantasy"
- git config --local user.email "larry.fantasy@gmail.com"
deploy:
  provider: releases
  api_key: 
    secure: GH_TOKEN
  file: README.md
  skip_cleanup: true
  draft: true
  on:
    tags: true
env:
  global:
    secure: HkWYTJJkW2WGRtjJhFZ2/c5A4VOUImpndHKR4b9vfKPqqOa38bSOC/gj5L50FpECLhCrdTwegXKCVP4sapx0Nrwm/rKWlrbBZpkpX+zTYaZIOTjbaChZOwu8OOY0C1ZBeoQ2ihsI5KA8tlZVRp6Aka7B8piq/ZVhOyC0XQ4wq9NK6lu9bbAY/O1WfxPEMU6+V9r5qj5rDC6p0raiAF/L4V4pAx+Kgs5v76A9oHFpl9SYFp5mBEEzGKSTv+hCyXMNYayK9cn9C0U3DvjoxZEvHaZ1pPata41LIUBA9E3LV8SGaFG5iVsPxHuusQJeE4ldvdZ3Yq9yWIDxmV6Na8ivQ2tmHAHhnl0gM7/kmrQb/EFIkkM0LLjDeyKyJuEC9IF23XtRBmtKqYsHuuA0dxjHuUaLHq/adgSOV9Z4Lngo4X6Wn70oHb9R6GLlh4Xw4ElRRRI5NXtII1Haypl1ufttRpeMcaxoqWTlVDs7vmu3RLr17ImF7mV+M3+Z7J9PoPNc90NNmuIUPNt/SN9fdBwoUvN1dAh+8UERSKuLWHlRNb8ZSgQouyVyi0kR+FU/SPuf4VKcHcmx+Y9iBWRCscRqvyBlHR5fzAK5jDYVnUq/EneJM/fj1ZXLmoxQbgxaH1twcwTpC9eVwRLw2XCB+H0oT/kkd3iUL4DkcxF1igJIbZs=
