language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - graphviz

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
