language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - graphviz
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo run --verbose
- cargo build --release --verbose --all
- tar czvf rustgym-$TRAVIS_TAG.tar.gz target/release
before_deploy:
- git config --local user.name "Larry Fantasy"
- git config --local user.email "larry.fantasy@gmail.com"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
  - README.md
  - rustgym-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true