language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - graphviz
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo run --verbose
before_deploy:
- git config --local user.name "Larry Fantasy"
- git config --local user.email "larry.fantasy@gmail.com"
deploy:
  provider: releases
  api_key:
    secure: "Uxo69U+6YMtPAIA9vZ7HLzwhEJCXYOQ3+XcghzuVjuUHxeUMd/pNQhJjDTvmHWAcHGPBp3DlGpUCFILD9Zu5YQdBeIJWnnHXSCTzEGw2XLd+gkpvzioQEkeFl9T4lVsDpQ9If74U/aMd5bXnMXhrQhyG5T8Xk1KXmXnGf1siQUabMIDeIe7oVQalMHGCOBbQpwhHG61IdS3RCXfZT+lt+DlPTNHC2N6l4u4GqBsY3+28SAw9+2tgzbJYREHIOibhw4Temr0kKnNU1R2bBBZJZvCH9Oa6uHZx70NJfScDr6HRf152+skctz9dRc3rn3kMdYzcJiqPRfsRzsUpzDG9+6GLeSQfW2GN16D7mb02/wvuYJqPHh/VrecEmabx8ukSsbAKIO35tStHNjFzwMbEJVW6EzJlUL04z6OQVHg8M6OoHiXHN8LiRaG9N8dKqD0I8Ib+aC3HUygsxNf0LfhJqnmi8L6hdNCIb5lUVHqZQqs9hQiPWXq+0cdTB3mIxvkBGg+3nyyYEwOiZrPJlAnouReC9D5VLx4tewq8z/oRcUFF9KreqlOe7tRYntqAbuPvzDd/ASVCfHWwoHkhFi4GSM4iqqGoKR+n7t10TbCGYENJShf+3TiqMySOv88Z4o9nlYJlW570UzTNeppMiiP/64eL40ZVWEvX0/Ap+9669lI="
  file: README.md
  skip_cleanup: true
  draft: true
  on:
    tags: true