language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - graphviz
script:
- cargo install diesel_cli --no-default-features --features sqlite
- cargo build --verbose --all
- cargo test --verbose --all
before_deploy:
- git config --local user.name "Larry Fantasy"
- git config --local user.email "larry.fantasy@gmail.com"
- diesel setup --database-url rustgym.sqlite
- cargo run --bin rustgym-readme --verbose
- cargo build --release --verbose --all
- tar czvf rustgym.tar.gz target/release
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
  - README.md
  - rustgym.tar.gz
  - rustgym.sqlite
  skip_cleanup: true
  on:
    tags: true