[config]
default_to_workspace = false

[tasks.rm_sqlite]
script = ["rm rustgym.sqlite"]

[tasks.migration]
script = ["diesel migration run --database-url rustgym.sqlite"]

[tasks.readme]
script = ["cargo run --bin rustgym-readme"]
dependencies = ["rm_sqlite", "migration"]

[tasks.copy-server]
script = 'cp target/release/rustgym-server rustgym-server'

[tasks.copy-ingest]
script = 'cp target/release/rustgym-ingest rustgym-ingest'

[tasks.wasm-pack]
script = 'wasm-pack build wasm --target web --out-dir ../pkg'

[tasks.archive-wasm]
script = "tar -czvf pkg.tar.gz pkg"

[tasks.archive-static]
script = "tar -czvf static.tar.gz static"

[tasks.watch-wasm]
run_task = { name = ["wasm-pack"] }
watch = { postpone = true, watch = ["./wasm/", "./msg/"] }

[tasks.watch-server]
script = "cargo watch -w server -w msg -x 'run --bin rustgym-server'"
dependencies = ["wasm-pack"]

[tasks.dev]
run_task = { name = ["watch-server", "watch-wasm"], parallel = true }
