[config]
default_to_workspace = false

[tasks.rm_sqlite]
script = ["rm rustgym.sqlite"]

[tasks.migration]
script = ["diesel migration run --database-url rustgym.sqlite"]

[tasks.readme]
script = ["cargo run --bin rustgym-readme"]
dependencies = ["rm_sqlite", "migration"]

[tasks.docker]
script = 'docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust:1.48.0 cargo build --release'

[tasks.archive]
script = 'tar czvf rustgym.tar.gz target/release'

[tasks.deploy]
script = [
    "echo $TAG",
    "git tag $TAG",
    "git push origin $TAG",
    "gh release create $TAG rustgym.sqlite rustgym.tar.gz"
]
dependencies = ["readme", "docker", "archive"]

[tasks.dev]
script = "cargo watch -x 'run --bin rustgym-server'"
