[config]
default_to_workspace = false

[tasks.rm_sqlite]
script = ["rm rustgym.sqlite"]

[tasks.migration]
script = ["diesel migration run --database-url rustgym.sqlite"]

[tasks.readme]
script = ["cargo run --bin rustgym-readme"]
dependencies = ["rm_sqlite", "migration"]

[tasks.mac]
script = 'docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust:1.48.0 cargo build --release'

[tasks.linux]
script = 'cargo build --release --verbose'

[tasks.copy-server]
script = 'cp target/release/rustgym-server rustgym-server'

[tasks.wasm-pack]
script = 'wasm-pack build client --target web'

[tasks.copy-client]
script = 'cp -R client/pkg/ pkg/'

[tasks.archive-client]
script = "tar -czvf pkg.tar.gz pkg"
dependencies = ["copy-client"]


[tasks.watch-client]
run_task = {name = ["wasm-pack", "copy-client"]}
watch = { postpone = true,  watch = ["./client/"]}

[tasks.deploy]
script = [
    "echo $TAG",
    "git tag $TAG",
    "git push origin $TAG",
    "gh release create $TAG rustgym.sqlite rustgym-server"
]
dependencies = ["readme", "mac", "copy-server", "wasm-pack", "copy-client"]

[tasks.watch-server]
script = "cargo watch -x 'run --bin rustgym-server'"

[tasks.dev]
run_task = { name = ["watch-server", "watch-client"], parallel = true }

[tasks.restart]
script = "cd infra; ./deploy.sh"
dependencies = ["deploy"]
