[package]
name = "rustgym-wasm"
version = "0.1.0"
authors = ["Larry Fantasy <larry.fantasy@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
rustgym-message = { path = "../message" }
wasm-bindgen = "0.2.63"
js-sys = "0.3.46"
console_error_panic_hook = { version = "0.1.6", optional = true }
web-sys = { version = "0.3.46", features = [
    "Window",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
    "Location",
] }
serde_json = "1.0.61"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
