[package]
name = "rustgym-wasm"
version = "0.1.0"
authors = ["Larry Fantasy <larry.fantasy@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
rustgym-msg = { path = "../msg" }
wasm-bindgen = "0.2.63"
js-sys = "0.3.46"
console_error_panic_hook = { version = "0.1.6", optional = true }
web-sys = { version = "0.3.46", features = [
    "Window",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
    "Location",
] }
serde_json = "1.0.62"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
seed = "0.8.0"
anyhow = "1.0.38"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
