name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install cargo-make
      run: cargo install cargo-make --verbose
    - name: Install diesel_cli
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Migration
      run: cargo make migration
    - name: Readme
      run: cargo make readme
    - name: Archive
      run: cargo make archive
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload sqlite
      id: upload-sqlite 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rustgym.sqlite
        asset_name: rustgym.sqlite
        asset_content_type: application/vnd.sqlite3
    - name: Upload archive
      id: upload-archive 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rustgym.tar.gz
        asset_name: rustgym.tar.gz
        asset_content_type: application/tar+gzip
