name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-make
      run: cargo install cargo-make --verbose
    - name: Install diesel_cli
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Migration
      run: cargo make migration
    - name: Readme
      run: cargo make readme
